In [1]:
import torch

print(torch.__version__)

2.5.1+cpu


In [19]:
# create tensor
torch.empty(2,4)

torch.ones(2,3 , dtype= torch.float64)

a = torch.tensor([[2,3,4 ] ,[2,3 ,4 ]] , dtype= torch.float64)
a.shape

torch.Size([2, 3])

In [21]:
# create tensor of same size 
torch.empty_like(a)

torch.zeros_like(a)

torch.ones_like(a)

torch.rand_like(a) # genreta values betwwen 0-1

tensor([[0.3687, 0.0625, 0.4248],
        [0.4736, 0.9446, 0.8696]], dtype=torch.float64)

In [49]:
# Data type in tensor
a.dtype

b = torch.tensor([ -.5,2.3 , 4, 4] , dtype= torch.float64)

# b.to(torch.int32)

tensor([0, 2, 4, 4], dtype=torch.int32)

In [52]:
# maths on tensor - scaler 
b + 1

b*3

b/3

(b*100)//2

((b*100)//2)%3

b.abs()
torch.neg(b)
torch.abs(b)
b.ceil()
b.floor()
torch.clamp(b , 2,3 )

tensor([2.0000, 2.3000, 3.0000, 3.0000], dtype=torch.float64)

In [73]:
# maths on tensor - between two tensor
a = torch.rand(2,3)
b = torch.rand(2,3)

a+b
a+b
a*b
a/b
a//b
a%b

# torch.matmul(a,b)

tensor([[0.0030, 0.0963, 0.1353],
        [0.0065, 0.5094, 0.2591]])

In [ ]:
# Reducing matrix
a = torch.ones(3,2)

torch.sum(a)
torch.sum(a , dim = 0) # along column
torch.mean(a , dim = 1) # along row
torch.max(a)
torch.prod(a,dim = 0)
torch.std( a , dim = 1)
torch.argmax(a)
torch.argmin(a)
torch.relu(a)
torch.softmax(a , dim = 0)

trans_a = torch.transpose(a , 1,0)
trans_a

temp = torch.rand(3,3)
torch.det(temp)

tensor(0.0472)

In [2]:
# comparision operation
i = torch.tensor([[2,3,4], [3,4,5]] , dtype= torch.float64)
j = torch.tensor([[4,5,6],[1,2,4]], dtype= torch.float64)

i>j
i<=j
i!= j
i == j


tensor([[False, False, False],
        [False, False, False]])

In [98]:
# Inplace Operation
j.add_(i)
j.sub_(i)
torch.relu_(i)

tensor([[2., 3., 4.],
        [3., 4., 5.]], dtype=torch.float64)

In [7]:
# Copy a tensor
i = j
id(i) , id(j) # problem

i = torch.clone(j) # solution
id(i) , id(j)

i , j

(tensor([[4., 5., 6.],
         [1., 2., 4.]], dtype=torch.float64),
 tensor([[4., 5., 6.],
         [1., 2., 4.]], dtype=torch.float64))

In [15]:
# Tensor operation using GPU
torch.cuda.is_available()

device = torch.device("cpu") # for cpu add "cuda" instead of "cpu"

torch.rand(2,3 , dtype= torch.float64 , device= device)

a = torch.rand(4,5)
b = torch.rand(5,6)

a = a.to(device=device)
b = b.to(device=device)

torch.matmul(a ,b)

tensor([[1.3421, 1.1887, 1.0881, 0.9220, 0.6148, 1.0636],
        [0.5013, 0.5732, 0.5361, 0.5973, 0.3094, 0.6367],
        [1.7832, 1.4466, 1.2973, 0.9179, 0.7205, 1.0791],
        [1.5278, 0.9475, 0.7860, 0.5364, 0.3885, 0.7419]])

In [25]:
# Reshaping Tensors

a = torch.ones(4,1)
a.reshape(2 , 2) # original shape product =  reshaped shape product

a.flatten()

b = torch.ones(3,4,5)
b.permute(1,0 ,2).shape 

b.unsqueeze(0).shape

torch.Size([1, 3, 4, 5])

In [34]:
# NUmpy to Torch
import numpy as np

a = np.array([1,3,4,5])
type(a)
a = torch.from_numpy(a) # Numpy array to tensor
type(a)

b = torch.tensor([1,2 , 3,4 ])
type(b)
b = b.numpy()
type(b)

numpy.ndarray