In [1]:
import torch

print(torch.__version__)

2.5.1+cpu


In [2]:
# create tensor
torch.empty(2,4)

torch.ones(2,3 , dtype= torch.float64)

a = torch.tensor([[2,3,4 ] ,[2,3 ,4 ]] , dtype= torch.float64)
a.shape

torch.Size([2, 3])

In [3]:
# create tensor of same size 
torch.empty_like(a)

torch.zeros_like(a)

torch.ones_like(a)

torch.rand_like(a) # genreta values betwwen 0-1

tensor([[0.5189, 0.6605, 0.3758],
        [0.5124, 0.6289, 0.9076]], dtype=torch.float64)

In [4]:
# Data type in tensor
a.dtype

b = torch.tensor([ -.5,2.3 , 4, 4] , dtype= torch.float64)

# b.to(torch.int32)

In [5]:
# maths on tensor - scaler 
b + 1

b*3

b/3

(b*100)//2

((b*100)//2)%3

b.abs()
torch.neg(b)
torch.abs(b)
b.ceil()
b.floor()
torch.clamp(b , 2,3 )

tensor([2.0000, 2.3000, 3.0000, 3.0000], dtype=torch.float64)

In [6]:
# maths on tensor - between two tensor
a = torch.rand(2,3)
b = torch.rand(2,3)

a+b
a+b
a*b
a/b
a//b
a%b

# torch.matmul(a,b)

tensor([[0.3628, 0.1295, 0.1326],
        [0.0158, 0.4813, 0.1605]])

In [7]:
# Reducing matrix
a = torch.ones(3,2)

torch.sum(a)
torch.sum(a , dim = 0) # along column
torch.mean(a , dim = 1) # along row
torch.max(a)
torch.prod(a,dim = 0)
torch.std( a , dim = 1)
torch.argmax(a)
torch.argmin(a)
torch.relu(a)
torch.softmax(a , dim = 0)

trans_a = torch.transpose(a , 1,0)
trans_a

temp = torch.rand(3,3)
torch.det(temp)

tensor(0.3247)

In [8]:
# comparision operation
i = torch.tensor([[2,3,4], [3,4,5]] , dtype= torch.float64)
j = torch.tensor([[4,5,6],[1,2,4]], dtype= torch.float64)

i>j
i<=j
i!= j
i == j


tensor([[False, False, False],
        [False, False, False]])

In [9]:
# Inplace Operation
j.add_(i)
j.sub_(i)
torch.relu_(i)

tensor([[2., 3., 4.],
        [3., 4., 5.]], dtype=torch.float64)

In [10]:
# Copy a tensor
i = j
id(i) , id(j) # problem

i = torch.clone(j) # solution
id(i) , id(j)

i , j

(tensor([[4., 5., 6.],
         [1., 2., 4.]], dtype=torch.float64),
 tensor([[4., 5., 6.],
         [1., 2., 4.]], dtype=torch.float64))

In [11]:
# Tensor operation using GPU
torch.cuda.is_available()

device = torch.device("cpu") # for cpu add "cuda" instead of "cpu"

torch.rand(2,3 , dtype= torch.float64 , device= device)

a = torch.rand(4,5)
b = torch.rand(5,6)

a = a.to(device=device)
b = b.to(device=device)

torch.matmul(a ,b)

tensor([[1.6352, 1.7477, 2.5755, 2.2724, 2.7095, 2.5869],
        [0.4486, 0.8401, 1.0211, 0.7839, 1.1493, 1.0826],
        [0.8314, 0.9847, 1.2334, 1.2303, 1.4476, 1.3873],
        [1.3702, 1.6120, 1.9183, 1.8423, 2.4025, 2.1910]])

In [12]:
# Reshaping Tensors

a = torch.ones(4,1)
a.reshape(2 , 2) # original shape product =  reshaped shape product

a.flatten()

b = torch.ones(3,4,5)
b.permute(1,0 ,2).shape 

b.unsqueeze(0).shape

torch.Size([1, 3, 4, 5])

In [13]:
# NUmpy to Torch
import numpy as np

a = np.array([1,3,4,5])
type(a)
a = torch.from_numpy(a) # Numpy array to tensor
type(a)

b = torch.tensor([1,2 , 3,4 ])
type(b)
b = b.numpy()
type(b)

numpy.ndarray